suborgrepos:
  - p*

repository:
  description: A template for platform services
  # homepage: https://github.com/uniphore/
  topics:
    - x-platform
    - platform
    - template
    - template-service
    - template-project
    - hello-world
    - helloworld
    - service

  # Keep this as true for most cases
  # A lot of the policies below cannot be implemented on bare repos
  # Pass true to create an initial commit with empty README.
  auto_init: true

  private: false
  visibility: internal
  has_issues: false
  has_projects: false
  has_wiki: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_auto_merge: true
  delete_branch_on_merge: true
  allow_update_branch: true

# The following attributes are applied to any repo within the org
# So if a repo is not listed above is created or edited
# The app will apply the following settings to it
labels:
  - name: bug
    color: d73a4a
  - name: do-not-merge
    color: FF0000
  - name: charts
    color: 8F6555
  - name: ci/cd
    color: C35B0E
  - name: deploy
    color: 15D21E
  - name: docker
    color: 87A89A
  - name: docs
    color: 0075ca
  - name: garden
    color: ededed
  - name: go
    color: 95558F
  - name: java
    color: AB3A4F
  - name: python
    color: 88AAFF
  - name: restapi
    color: 5D0CE6


# Collaborators: give specific users access to any repository.
# See https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator for available options
# The permission to grant the collaborator. Can be one of:
# * `pull` - can pull, but not push to or administer this repository.
# * `push` - can pull and push, but not administer this repository.
# * `admin` - can pull, push and administer this repository.
# * `<custom role> - Give the custom role name
# collaborators:
#   - username: drstrange
#     permission: push
#   - username: beetlejuice
#     permission: pull
#     exclude:
#       - actions-demo
# You can exclude a list of repos for this collaborator and all repos except these repos would have this collaborator
#   - username: thor
#     permission: push
#     include:
#       - actions-demo
#       - another-repo
# You can include a list of repos for this collaborator and only those repos would have this collaborator

# See https://developer.github.com/v3/teams/#add-or-update-team-repository for available options
# The permission to grant the team. Can be one of:
# * `pull` - can pull, but not push to or administer this repository.
# * `push` - can pull and push, but not administer this repository.
# * `admin` - can pull, push and administer this repository.
teams:
  - name: X-Platform
    permission: admin
  - name: RnD
    permission: push
    # exclude:
    #   - actions-demo
# You can exclude a list of repos for this collaborator and all repos except these repos would have this collaborator


branches:
  # If the name of the branch value is specified as `default`, then the app will create a branch protection rule to apply against the default branch in the repo
  - name: default
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 1
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: true
        # Whether the most recent reviewable push must be approved by someone other than the person who pushed it.
        require_last_push_approval: true
        # Allow specific users, teams, or apps to bypass pull request requirements. Set to null to disable.
        bypass_pull_request_allowances:
        # apps: []
          users: [platform-ci, bxsx]
          teams: []
        # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
        # dismissal_restrictions:
        #   users: []
        #   teams: []
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        # contexts: []
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: true
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        apps: []
        users: []
        teams: []

validator:
  pattern: '[a-zA-Z0-9_-]+_[a-zA-Z0-9_-]+.*'
