# This settings file can be used to create suborg-level settings

# List of repos that belong to the suborg
# You can use Glob patterns
suborgrepos:
  - poc1
  - poc2
  - poc3

# List of repos that belong to the suborg
#suborgteams:
#  - core

# List of repos that belong to the suborg based on custom properties
#suborgproperties:
#- EDP: true

# Every other property is the same as the org level settings and can be overridden here
repository:
  # A short description of the repository that will show up on GitHub
  description: description of the suborg repo today
