repository:
  name: poc1
  description: Platform CI/CD
  homepage: 
  topics:
    - platform
    - x-platform
    - cicd
    - cicd-pipeline
    - github-actions

  # Create the repo if it is not existing
  force_create: false

  # Use a template when creating the repo
  # template: template_repo

  # Keep this as true for most cases
  # A lot of the policies below cannot be implemented on bare repos
  # Pass true to create an initial commit with empty README.
  auto_init: true

  # Settings for Code security and analysis
  # Dependabot Alerts
  security:
    enableVulnerabilityAlerts: true
    enableAutomatedSecurityFixes: true

  private: true
  visibility: internal
  has_issues: false
  has_projects: false
  has_wiki: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_auto_merge: false
  delete_branch_on_merge: true

# The following attributes are applied to any repo within the org
# So if a repo is not listed above is created or edited
# The app will apply the following settings to it
labels:
  include:
    - name: bugtwo
      color: d73a4a
      description: An issue with the system
    - name: do-not-merge
      color: d73a4a
      description: Do not merge the PR
    - name: do-not-mergelevel
      color: d73a4a
      description: Do not merge the PR
      # exclude:
      #   # don't delete any labels created on GitHub that starts with "release"
      #   - name: ^release

# See https://developer.github.com/v3/teams/#add-or-update-team-repository for available options
# The permission to grant the team. Can be one of:
# * `pull` - can pull, but not push to or administer this repository.
# * `push` - can pull and push, but not administer this repository.
# * `admin` - can pull, push and administer this repository.
teams:
  - name: X-Platform
    permission: admin
  - name: RnD
    permission: push
  - name: delivery
    permission: pull

autolinks:
  - key_prefix: XPLAT-
    url_template: https://uniphore.atlassian.net/browse/XPLAT-<num>
  - key_prefix: XPDEVOPS-
    url_template: https://uniphore.atlassian.net/browse/XPDEVOPS-<num>
  - key_prefix: XPSERVICES-
    url_template: https://uniphore.atlassian.net/browse/XPSERVICES-<num>

branches:
  - name: default
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
        bypass_pull_request_allowances:
          apps: []
          users: []
          teams: []
        dismissal_restrictions:
          users: [bxsx]
          teams: []
      required_status_checks:
        strict: true
        contexts:
          - validate-yaml
          - validate-actions
          - validate-branch-refs
      enforce_admins: true
      restrictions:
        apps: []
        users: []
        teams: []

  - name: custom/interact-*
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
        bypass_pull_request_allowances:
          apps: []
          users: []
          teams: []
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts:
          - validate-yaml
          - validate-actions
          - validate-branch-refs
      enforce_admins: true
      restrictions:
        apps: []
        users: []
        teams: [interact-devops]

  - name: custom/*
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        require_last_push_approval: true
        bypass_pull_request_allowances:
          apps: []
          users: []
          teams: []
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts:
          - validate-yaml
          - validate-actions
          - validate-branch-refs
      enforce_admins: true
      restrictions:
        apps: []
        users: []
        teams: []

validator:
  pattern: '[a-zA-Z0-9_-]+_[a-zA-Z0-9_-]+.*'
